let GlobalState = {
  matchNumber: 1,
  driverStation: "",
  teamNumber: "",
  preload: false,
  startingPosition: "",
  wingPickupAuto: 0,
  totalPickupAuto: 0,
  centerLine1: false,
  centerLine2: false,
  centerLine3: false,
  centerLine4: false,
  centerLine5: false,
  leave: false,
  scoredAmpAuto: 0,
  scoredSpeakerAuto: 0,
  missedAmpAuto: 0,
  missedSpeakerAuto: 0,
  droppedAuto: 0,
  humanLoadPickup: 0,
  wingPickupTele: 0,
  noMansLandPickup: 0,
  totalPickupTele: 0,
  droppedTele: 0,
  dies: 0,
  beaches: 0,
  tips: 0,
  ampScoredTele: 0,
  ampMissedTele: 0,
  speakerScoredTele: 0,
  speakerMissedTele: 0,
  hang: false,
  harmonyHang: false,
  parked: false,
  trap: false,
  comments: "",
};

export default GlobalState;
